package com.cointrend.domain.models

const val NUM_TOP_COINS_TO_SHOW = 250

const val TOP_COINS_MINUTES_REFRESH_PERIOD = 60
const val TRENDING_COINS_MINUTES_REFRESH_PERIOD = 120
const val FAVOURITE_COINS_MINUTES_REFRESH_PERIOD = 30
const val COIN_MARKET_DATA_REFRESH_PERIOD = 120
